pages: # the job must be named pages
  image: node:latest
  stage: deploy
  script:
    - echo "VITE_FIREBASE_API_KEY=$FIREBASE_API_KEY" >> .env
    - echo "VITE_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> .env
    - echo "VITE_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
    - echo "VITE_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> .env
    - echo "VITE_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> .env
    - echo "VITE_FIREBASE_APP_ID=$FIREBASE_APP_ID" >> .env
    - echo "VITE_RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY" >> .env
    - echo "VITE_API_BASE_URL=$API_BASE_URL" >> .env
    - npm ci
    - npm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
    - cp public/index.html public/404.html # Fix the 404 problem when reloading pages
    # optionally, you can activate gzip support with the following line:
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - main